#!/bin/bash

fruits=("apple" "banana" "orange")

# one element
echo "${fruits[0]}"

# all element
echo "${fruits[@]}"

# length
echo "${#fruits[@]}"

# add element
fruits+=("grape")

echo "${fruits[@]}"

fruits=("${fruits[@]/banana}")

echo "${fruits[@]}"

echo "${#fruits[@]}"
